ALTER TABLE PaperParagraph MODIFY title VARCHAR(255)  CHARACTER SET UTF8 DEFAULT NULL;

ALTER TABLE PaperParagraph MODIFY content VARCHAR(10240)  CHARACTER SET UTF8 DEFAULT NULL;

ALTER TABLE Paper add COLUMN priority BIGINT;

UPDATE Paper set priority = id;

ALTER TABLE Paper DROP COLUMN isRecom;